#!/usr/bin/env bash

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# bar settings
yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp

yabai -m config external_bar                 all:39:0
yabai -m config top_padding                  10
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   5

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# float settings windows
yabai -m rule --add title='Settings$' manage=off

# ignore these apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Alfred Preferences$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^Music$" manage=off
yabai -m rule --add app="Microsoft Teams$" manage=off
yabai -m rule --add app="^CleanShot X$" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^1Password$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Ivory$" manage=off

# Web browsers
yabai -m rule --add app="^Google Chrome|Firefox$" space=2
# Text editors
yabai -m rule --add app="^(Code|RStudio)$" space=3
# Jetbrains apps
apps="^(IntelliJ IDEA|WebStorm|RubyMine|PyCharm|DataGrip)$"
yabai -m rule --add app="${apps}" space=4  manage=off
# Terminal
yabai -m rule --add app="^(Alacritty|Kitty)$" space=1
# Music
yabai -m rule --add app="^(Spotify|Amazon Music)$" space=5
# Social
yabai -m rule --add app="^(Slack|WhatsApp|Microsoft Teams)$" space=6